services:
  - type: web
    name: PROJECT-LUDO
    env: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "*"
      - key: CORS_METHODS
        value: "GET,POST,PUT,DELETE,OPTIONS"
      - key: CORS_HEADERS
        value: "Content-Type,Authorization"
      - key: BACKEND_URL
        value: https://project-ludo.onrender.com
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app
