services:
  - type: web
    name: ludo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_BASE_URL
        value: https://openrouter.ai/api/v1
      - key: OPENROUTER_SITE_URL
        value: https://ludo-performance-suite.onrender.com
      - key: OPENROUTER_SITE_NAME
        value: Ludo Performance Suite
      - key: BACKEND_URL
        value: https://ludo-backend.onrender.com
      - key: FRONTEND_URL
        value: https://ludo-frontend.onrender.com
